
module.exports={
  routes:[
    {
    method:"POST",
    path:"/create-customerMember",
    handler:"customer.customerMember"
  },
    {
    method:"POST",
    path:"/create-customerContract",
    handler:"customer.customerContract"
  },
  {
    method:"POST",
    path:"/create-customerContract2",
    handler:"customer.customerContract2"
  },
]
}
